### ISSUE TITLE
Update stable version in repo from 0.0.0 to 0.0.14

### ISSUE THREAD

**Issue by GermanBluefox** [XHunter74/ioBroker.gree-hvac#11]
# Think about adding version 0.0.14 to stable repository.
**Version**: stable=**0.0.0** (0 days old) => latest=**0.0.14** (30 days old)
**Installs**: stable=**0** (0%), latest=**9** (100%), total=**9**

Click to use [developer portal](https://www.iobroker.dev/adapter/gree-hvac/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json)

**Do not close this issue manually as a new issue will be created if condition for update still exists.**

Please drop a comment if any reason exists which blocks updating to version 0.0.14 at this time.

Note: This is an automatically generated message and not personally authored by bluefox!
      @mcm1957 for evidence

**Comment by mcm1957** [comment]
outdated - wait for 1.0.0

**Comment by XHunter74** [comment]
1.0.0 is ready
