### ISSUE TITLE
Please add how to use to readme.md

### ISSUE THREAD

**Issue by Tempmail1234-pass** [XHunter74/ioBroker.gree-hvac#14]
I installed the package, how do I use it? What file to run? Where to put the IP of the A/C?

**Comment by XHunter74** [comment]
Before using this package you should install ioBroker platform https://www.iobroker.net/

**Comment by Tempmail1234-pass** [comment]
Can you help me with contolling my gree A/C without iobroker?
I am tyring this one
https://github.com/cmroche/greeclimate/issues/75
