### ISSUE TITLE
adapter is green and I don't see any device

### ISSUE THREAD

**Issue by di3t0** [XHunter74/ioBroker.gree-hvac#20]
the adapter is green and I don't see any device and this is in the log:
Received message from 502cc605d5a1 (192.168.100.211:7000) {"t":"pack","i":1,"uid":0,"cid":"502cc605d5a1","tcid":"app","pack":"LP24Ek0OaYogxs3iQLjL4CVWHqmPoWzCNdstE6VtRN5YT1PXPBDouOPiWHaG4G8lz22fUZtUbkblUYF5BzlKDV9xeQzMlsaP4RKBtrnsDrPgJXA+/2/qaGLK2Z7N/04mLjfzIBDIkDxmTYsl4aiW1+80HbfgK3MNVtBb+mRtQFwvWGtrb35TAKQLbuUeHhrjkywWYwaOwxo65kKReDaAYU+t/W6ao6KLeI6AQs8sVr6ZbdEmdMsvWjDwsWTPw4iozbbXHI8ghbocDlA7fUL03g=="}

![image](https://github.com/user-attachments/assets/4f59234f-5261-4f4c-9d50-f0e9990029c1)

**Comment by di3t0** [comment]
![image](https://github.com/user-attachments/assets/45e68e6c-2ccf-4288-99ab-4c3aa7ec00f2)

**Comment by cont1nuity** [comment]
Same issue with FW updated to v1.23
Do you need any further information or can I assist in further testing/debugging?

**Comment by cont1nuity** [comment]
It appears that GCM encryption is used in newer firmware versions, as alternative to AES ECB.
Examples from Home Assistant projects: 
https://github.com/cmroche/greeclimate/commit/7122cdd82597af82109a17bc32dcbfb97c78073c
https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/blob/5d6be580303b727cca9c60bb90772a60db25e736/custom_components/gree/climate.py#L366

**Comment by XHunter74** [comment]
> It appears that GCM encryption is used in newer firmware versions, as alternative to AES ECB. Examples from Home Assistant projects: [cmroche/greeclimate@7122cdd](https://github.com/cmroche/greeclimate/commit/7122cdd82597af82109a17bc32dcbfb97c78073c) https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent/blob/5d6be580303b727cca9c60bb90772a60db25e736/custom_components/gree/climate.py#L366
> 
> Edit: Potentially the device key changed.

will check and try fix.

**Comment by cont1nuity** [comment]
Thank you.
I am not too good with js/node, but I can test things here.
I suggest adding an option or auto-detection for which encryption is to be used with the device.

**Comment by XHunter74** [comment]
@di3t0, seems your device did not register in gree app or is not connected to internet.
The decoded response is:
`{
    "t": "dev",
    "cid": "502cc605d5a1",
    "bc": "gree",
    "brand": "gree",
    "catalog": "gree",
    "mac": "502cc605d5a1",
    "mid": "3018",
    "model": "gree",
    "name": "c605d5a1",
    "series": "gree",
    "vender": "1",
    "ver": "V1.0.0.0",
    "lock": 0
}`

The correct response should contain   { "t": "bindok", ...

**Comment by XHunter74** [comment]
@di3t0 , you can try version 1.1.0 which available from npm. Please let me know about any results.

**Comment by di3t0** [comment]
it works, great. Thank you very much.
![image](https://github.com/user-attachments/assets/be73e36b-4479-482d-a21f-6ca51808ac6a)
